CREATE TABLE IF NOT EXISTS `Blog_User`(
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` VARCHAR(50) NOT NULL COMMENT  '用户名',
    `password` VARCHAR(100) NOT NULL COMMENT '密码',
    `email` VARCHAR(100) NOT NULL COMMENT '邮箱',
#     `group` VARCHAR(50) NOT NULL COMMENT '用户组',
#     `permissions` varchar(100) DEFAULT 'guest' COMMENT '权限',
    PRIMARY KEY (id), UNIQUE (name)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户表';

CREATE TABLE IF NOT EXISTS `User_Group`(
      `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
      `user_id` BIGINT(20) DEFAULT NULL COMMENT '组id',
      `group_id` BIGINT(20) DEFAULT NULL COMMENT '权限id',
      PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '组拥有的权限';